#!/usr/bin/env python3
"""Interactive setup for cterm. Writes cterm.local and cterm.local.cmd."""
import os
import sys
from pathlib import Path

REPO = Path(__file__).resolve().parent.parent

AGENTS = ['claude', 'copilot', 'codex', 'gemini']
DEFAULT_FONT = 'JetBrainsMono Nerd Font'
DEFAULT_FONT_SIZE = 11


def ask(prompt, default=None, choices=None):
    suffix = ''
    if choices:
        suffix = f" [{'/'.join(choices)}]"
    if default is not None:
        suffix += f" (default: {default})"
    while True:
        ans = input(f"{prompt}{suffix}: ").strip()
        if not ans and default is not None:
            return default
        if choices and ans not in choices:
            print(f"  pick one of: {', '.join(choices)}")
            continue
        if ans:
            return ans


def ask_yes_no(prompt, default='n'):
    ans = ask(prompt, default=default, choices=['y', 'n'])
    return ans == 'y'


def main():
    print("cterm setup\n-----------")

    agent = ask("Default agent CLI", default='claude', choices=AGENTS)
    font = ask("Font name", default=DEFAULT_FONT)
    size_raw = ask("Font size", default=str(DEFAULT_FONT_SIZE))
    try:
        size = int(size_raw)
    except ValueError:
        print(f"  invalid size, using {DEFAULT_FONT_SIZE}")
        size = DEFAULT_FONT_SIZE
    use_user_nvim = ask_yes_no("Use your own nvim config (instead of bundled)?", default='n')

    sh = REPO / 'cterm.local'
    sh.write_text(
        '# Generated by scripts/setup.py — edit freely or rerun: cterm --setup\n'
        f'CTERM_DEFAULT_AGENT={agent}\n'
        f'CTERM_FONT="{font}"\n'
        f'CTERM_FONT_SIZE={size}\n'
        f'CTERM_USE_USER_NVIM={"1" if use_user_nvim else "0"}\n'
    )

    cmd = REPO / 'cterm.local.cmd'
    cmd.write_text(
        '@echo off\r\n'
        'rem Generated by scripts/setup.py - edit freely or rerun: cterm --setup\r\n'
        f'set "CTERM_DEFAULT_AGENT={agent}"\r\n'
        f'set "CTERM_FONT={font}"\r\n'
        f'set "CTERM_FONT_SIZE={size}"\r\n'
        f'set "CTERM_USE_USER_NVIM={"1" if use_user_nvim else "0"}"\r\n'
    )

    print(f"\nWrote {sh}")
    print(f"Wrote {cmd}")
    print("Done. Run `cterm` to launch.")


if __name__ == '__main__':
    try:
        main()
    except (KeyboardInterrupt, EOFError):
        print("\nSetup cancelled.")
        sys.exit(1)
