#!/usr/bin/env python3
"""Interactive setup for cterm. Writes cterm.local and cterm.local.cmd,
optionally enables the caveman plugin globally."""
import json
import os
import sys
from pathlib import Path

REPO = Path(__file__).resolve().parent.parent

AGENTS = ['claude', 'copilot', 'codex', 'gemini']
DEFAULT_FONT = 'JetBrainsMono Nerd Font'
DEFAULT_FONT_SIZE = 11


def ask(prompt, default=None, choices=None):
    suffix = ''
    if choices:
        suffix = f" [{'/'.join(choices)}]"
    if default is not None:
        suffix += f" (default: {default})"
    while True:
        ans = input(f"{prompt}{suffix}: ").strip()
        if not ans and default is not None:
            return default
        if choices and ans not in choices:
            print(f"  pick one of: {', '.join(choices)}")
            continue
        if ans:
            return ans


def ask_yes_no(prompt, default='n'):
    ans = ask(prompt, default=default, choices=['y', 'n'])
    return ans == 'y'


def caveman_config_dir():
    if os.environ.get('XDG_CONFIG_HOME'):
        return Path(os.environ['XDG_CONFIG_HOME']) / 'caveman'
    if sys.platform == 'win32':
        return Path(os.environ.get('APPDATA', Path.home() / 'AppData' / 'Roaming')) / 'caveman'
    return Path.home() / '.config' / 'caveman'


def enable_caveman():
    cfg_dir = caveman_config_dir()
    cfg_dir.mkdir(parents=True, exist_ok=True)
    cfg_path = cfg_dir / 'config.json'
    cfg_path.write_text(json.dumps({'defaultMode': 'ultra'}, indent=2) + '\n')
    print(f"  wrote {cfg_path} (defaultMode: ultra)")

    settings_path = Path.home() / '.claude' / 'settings.json'
    settings_path.parent.mkdir(parents=True, exist_ok=True)
    settings = {}
    if settings_path.exists():
        try:
            settings = json.loads(settings_path.read_text())
        except Exception:
            print(f"  warning: {settings_path} is not valid JSON; leaving as is")
            return

    settings.setdefault('extraKnownMarketplaces', {})['caveman'] = {
        'source': {'source': 'github', 'repo': 'JuliusBrussee/caveman'}
    }
    settings.setdefault('enabledPlugins', {})['caveman@caveman'] = True

    settings_path.write_text(json.dumps(settings, indent=2) + '\n')
    print(f"  updated {settings_path} (caveman marketplace + plugin enabled)")
    print("  caveman plugin will install on next claude session.")


def main():
    print("cterm setup\n-----------")

    agent = ask("Default agent CLI", default='claude', choices=AGENTS)
    font = ask("Font name", default=DEFAULT_FONT)
    size_raw = ask("Font size", default=str(DEFAULT_FONT_SIZE))
    try:
        size = int(size_raw)
    except ValueError:
        print(f"  invalid size, using {DEFAULT_FONT_SIZE}")
        size = DEFAULT_FONT_SIZE
    use_user_nvim = ask_yes_no("Use your own nvim config (instead of bundled)?", default='n')

    install_caveman = False
    if agent == 'claude':
        install_caveman = ask_yes_no(
            "Install caveman plugin (terse output, default mode: ultra)?", default='n')

    sh = REPO / 'cterm.local'
    sh.write_text(
        '# Generated by scripts/setup.py — edit freely or rerun: cterm --setup\n'
        f'CTERM_DEFAULT_AGENT={agent}\n'
        f'CTERM_FONT="{font}"\n'
        f'CTERM_FONT_SIZE={size}\n'
        f'CTERM_USE_USER_NVIM={"1" if use_user_nvim else "0"}\n'
    )

    cmd = REPO / 'cterm.local.cmd'
    cmd.write_text(
        '@echo off\r\n'
        'rem Generated by scripts/setup.py - edit freely or rerun: cterm --setup\r\n'
        f'set "CTERM_DEFAULT_AGENT={agent}"\r\n'
        f'set "CTERM_FONT={font}"\r\n'
        f'set "CTERM_FONT_SIZE={size}"\r\n'
        f'set "CTERM_USE_USER_NVIM={"1" if use_user_nvim else "0"}"\r\n'
    )

    print(f"\nWrote {sh}")
    print(f"Wrote {cmd}")

    if install_caveman:
        print("\nEnabling caveman globally...")
        enable_caveman()

    print("\nDone. Run `cterm` to launch.")


if __name__ == '__main__':
    try:
        main()
    except (KeyboardInterrupt, EOFError):
        print("\nSetup cancelled.")
        sys.exit(1)
