@echo off
setlocal enabledelayedexpansion

set "REPO=%~dp0.."
for %%I in ("%REPO%") do set "REPO=%%~fI"
set "REPO_FWD=%REPO:\=/%"

set "DEFAULT_FONT=JetBrainsMono Nerd Font"
set "DEFAULT_SIZE=11"
set "FONT_URL=https://github.com/ryanoasis/nerd-fonts/releases/latest/download/JetBrainsMono.zip"

echo cterm setup
echo -----------

:: ── Agent ─────────────────────────────────────────────────────────────────────
:ask_agent
set /p "AGENT=Default agent CLI [claude/copilot/codex/gemini] (default: claude): "
if "!AGENT!"=="" set "AGENT=claude"
if /i "!AGENT!"=="claude"  goto agent_ok
if /i "!AGENT!"=="copilot" goto agent_ok
if /i "!AGENT!"=="codex"   goto agent_ok
if /i "!AGENT!"=="gemini"  goto agent_ok
echo   pick one of: claude copilot codex gemini
goto ask_agent
:agent_ok

:: ── Font ──────────────────────────────────────────────────────────────────────
set /p "FONT=Font name (default: %DEFAULT_FONT%): "
if "!FONT!"=="" set "FONT=%DEFAULT_FONT%"

:: ── Font size ─────────────────────────────────────────────────────────────────
set /p "FSIZE=Font size (default: %DEFAULT_SIZE%): "
if "!FSIZE!"=="" set "FSIZE=%DEFAULT_SIZE%"
set /a "FSIZE_TEST=!FSIZE!" 2>nul
if "!FSIZE_TEST!"=="0" set "FSIZE=%DEFAULT_SIZE%"

:: ── Nvim config ───────────────────────────────────────────────────────────────
set "USE_NVIM=0"
set /p "TMP_YN=Use your own nvim config (instead of bundled)? [y/n] (default: n): "
if /i "!TMP_YN!"=="y" set "USE_NVIM=1"

:: ── Claude-specific ───────────────────────────────────────────────────────────
set "INST_SL=n"
set "INST_CAV=n"
if /i "!AGENT!"=="claude" (
  set "TMP_YN=y"
  set /p "TMP_YN=Install statusline globally? [y/n] (default: y): "
  if "!TMP_YN!"=="" set "TMP_YN=y"
  if /i "!TMP_YN!"=="y" set "INST_SL=y"

  set "TMP_YN=n"
  set /p "TMP_YN=Install caveman plugin (terse output, default mode: ultra)? [y/n] (default: n): "
  if /i "!TMP_YN!"=="y" set "INST_CAV=y"
)

:: ── Write cterm.local (bash format) ───────────────────────────────────────────
(
  echo # Generated by scripts/setup.cmd -- edit freely or rerun: cterm --setup
  echo CTERM_DEFAULT_AGENT=!AGENT!
  echo CTERM_FONT="!FONT!"
  echo CTERM_FONT_SIZE=!FSIZE!
  echo CTERM_USE_USER_NVIM=!USE_NVIM!
)>"%REPO%\cterm.local"

:: ── Write cterm.local.cmd ─────────────────────────────────────────────────────
(
  echo @echo off
  echo rem Generated by scripts/setup.cmd - edit freely or rerun: cterm --setup
  echo set "CTERM_DEFAULT_AGENT=!AGENT!"
  echo set "CTERM_FONT=!FONT!"
  echo set "CTERM_FONT_SIZE=!FSIZE!"
  echo set "CTERM_USE_USER_NVIM=!USE_NVIM!"
)>"%REPO%\cterm.local.cmd"

echo.
echo Wrote %REPO%\cterm.local
echo Wrote %REPO%\cterm.local.cmd

:: ── Statusline ────────────────────────────────────────────────────────────────
if /i "!INST_SL!"=="y" (
  echo.
  echo Configuring statusline globally...
  call :enable_statusline
)

:: ── Caveman ───────────────────────────────────────────────────────────────────
if /i "!INST_CAV!"=="y" (
  echo.
  echo Enabling caveman globally...
  call :enable_caveman
)

:: ── Font detection + install ──────────────────────────────────────────────────
if "!FONT!"=="%DEFAULT_FONT%" (
  call :maybe_install_font
)

echo.
echo Done. Run 'cterm' to launch.
goto :EOF

:: ─────────────────────────────────────────────────────────────────────────────
:enable_statusline
set "SETTINGS=%USERPROFILE%\.claude\settings.json"
set "SL_CMD=!REPO_FWD!/scripts/statusline.cmd"
node -e "const fs=require('fs'),p=process.argv[1],cmd=process.argv[2];let s={};if(fs.existsSync(p)){try{s=JSON.parse(fs.readFileSync(p,'utf8'));}catch(e){process.exit(0);}}s.statusLine={type:'command',command:cmd,refreshInterval:5};fs.mkdirSync(require('path').dirname(p),{recursive:true});fs.writeFileSync(p,JSON.stringify(s,null,2)+'\n');" "!SETTINGS!" "!SL_CMD!"
echo   Updated %USERPROFILE%\.claude\settings.json
exit /b

:enable_caveman
set "CAV_DIR=%APPDATA%\caveman"
if not exist "!CAV_DIR!" mkdir "!CAV_DIR!"
echo {"defaultMode":"ultra"}>"!CAV_DIR!\config.json"
echo   Wrote !CAV_DIR!\config.json
set "SETTINGS=%USERPROFILE%\.claude\settings.json"
node -e "const fs=require('fs'),p=process.argv[1];let s={};if(fs.existsSync(p)){try{s=JSON.parse(fs.readFileSync(p,'utf8'));}catch(e){process.exit(0);}}s.extraKnownMarketplaces=s.extraKnownMarketplaces||{};s.extraKnownMarketplaces.caveman={source:{source:'github',repo:'JuliusBrussee/caveman'}};s.enabledPlugins=s.enabledPlugins||{};s.enabledPlugins['caveman@caveman']=true;fs.mkdirSync(require('path').dirname(p),{recursive:true});fs.writeFileSync(p,JSON.stringify(s,null,2)+'\n');" "!SETTINGS!"
echo   Updated %USERPROFILE%\.claude\settings.json
echo   caveman plugin will install on next claude session.
exit /b

:maybe_install_font
powershell -NoProfile -Command ^
  "if ((Get-ChildItem (\"$env:WINDIR\Fonts\",\"$env:LOCALAPPDATA\Microsoft\Windows\Fonts\") -ErrorAction SilentlyContinue | Where-Object Name -match 'JetBrains') -or (Get-ItemProperty 'HKCU:\Software\Microsoft\Windows NT\CurrentVersion\Fonts' -ErrorAction SilentlyContinue).PSObject.Properties | Where-Object Name -match 'JetBrains') { exit 0 } else { exit 1 }" >nul 2>&1
if %errorlevel%==0 (
  echo   JetBrainsMono Nerd Font already installed.
  exit /b
)
set "TMP_YN=n"
set /p "TMP_YN=JetBrainsMono Nerd Font not found -- install it now? [y/n] (default: n): "
if /i not "!TMP_YN!"=="y" exit /b
echo   Downloading and installing JetBrainsMono Nerd Font...
powershell -NoProfile -ExecutionPolicy Bypass -Command ^
  "$url='%FONT_URL%';" ^
  "$tmp=[IO.Path]::GetTempPath()+'JetBrainsMono.zip';" ^
  "$dest=[IO.Path]::GetTempPath()+'JetBrainsMono';" ^
  "Invoke-WebRequest $url -OutFile $tmp;" ^
  "Expand-Archive -Path $tmp -DestinationPath $dest -Force;" ^
  "$fontsDir=[Environment]::GetFolderPath('LocalApplicationData')+'\Microsoft\Windows\Fonts';" ^
  "[void][IO.Directory]::CreateDirectory($fontsDir);" ^
  "$shell=New-Object -ComObject Shell.Application;" ^
  "$folder=$shell.Namespace($fontsDir);" ^
  "Get-ChildItem $dest -Recurse -Include *.ttf | ForEach-Object { $folder.CopyHere($_.FullName,0x10) };" ^
  "Remove-Item $tmp,$dest -Recurse -Force -ErrorAction SilentlyContinue;" ^
  "Write-Host '  Font installed.'"
exit /b
